<?php

namespace ContainerGlOv7Za;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ICxW05EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iCxW05E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iCxW05E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'r' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'reponse' => ['privates', '.errored..service_locator.iCxW05E.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.iCxW05E": it references class "App\\Entity\\Reponse" but no such service exists.'],
            'reponseRepository' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
        ], [
            'r' => 'App\\Repository\\ReclamationRepository',
            'reponse' => 'App\\Entity\\Reponse',
            'reponseRepository' => 'App\\Repository\\ReponseRepository',
        ]);
    }
}
