<?php

namespace Container2Jr83Hg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AwRdKq3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.awRdKq3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.awRdKq3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reponse' => ['privates', '.errored..service_locator.awRdKq3.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.awRdKq3": it references class "App\\Entity\\Reponse" but no such service exists.'],
        ], [
            'reponse' => 'App\\Entity\\Reponse',
        ]);
    }
}
