<?php

namespace Container2Jr83Hg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.awRdKq3.App\Entity\Reponse' shared service.
     *
     * @return \App\Entity\Reponse
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.awRdKq3": it references class "App\\Entity\\Reponse" but no such service exists.');
    }
}
