<?php

namespace ContainerEdcx8Zk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gu_OueiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gu.Ouei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gu.Ouei'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamation' => ['privates', '.errored..service_locator.Gu.Ouei.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.Gu.Ouei": it references class "App\\Entity\\Reclamation" but no such service exists.'],
            'reponseRepository' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
        ], [
            'reclamation' => 'App\\Entity\\Reclamation',
            'reponseRepository' => 'App\\Repository\\ReponseRepository',
        ]);
    }
}
