<?php

namespace ContainerEdcx8Zk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ID1oHHAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iD1oHHA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iD1oHHA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'reponse' => ['privates', '.errored..service_locator.iD1oHHA.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.iD1oHHA": it references class "App\\Entity\\Reponse" but no such service exists.'],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'reponse' => 'App\\Entity\\Reponse',
        ]);
    }
}
