<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVWh4cfJ\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVWh4cfJ/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVWh4cfJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVWh4cfJ\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerVWh4cfJ\srcApp_KernelProdContainer([
    'container.build_hash' => 'VWh4cfJ',
    'container.build_id' => '523795f0',
    'container.build_time' => 1681246187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVWh4cfJ');
