<?php

namespace ContainerIttsSet;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XhbWvTxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XhbWvTx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XhbWvTx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ReclamationController::delete' => ['privates', '.service_locator..6S4TIj', 'get_ServiceLocator__6S4TIjService', true],
            'App\\Controller\\ReclamationController::edit' => ['privates', '.service_locator..6S4TIj', 'get_ServiceLocator__6S4TIjService', true],
            'App\\Controller\\ReclamationController::index' => ['privates', '.service_locator.5_3wyDn', 'get_ServiceLocator_53wyDnService', true],
            'App\\Controller\\ReclamationController::new' => ['privates', '.service_locator.5_3wyDn', 'get_ServiceLocator_53wyDnService', true],
            'App\\Controller\\ReclamationController::show' => ['privates', '.service_locator.BbAkkvl', 'get_ServiceLocator_BbAkkvlService', true],
            'App\\Controller\\ReponseController::delete' => ['privates', '.service_locator.fgiOSH6', 'get_ServiceLocator_FgiOSH6Service', true],
            'App\\Controller\\ReponseController::edit' => ['privates', '.service_locator.fgiOSH6', 'get_ServiceLocator_FgiOSH6Service', true],
            'App\\Controller\\ReponseController::index' => ['privates', '.service_locator.BBl5klV', 'get_ServiceLocator_BBl5klVService', true],
            'App\\Controller\\ReponseController::new' => ['privates', '.service_locator.BBl5klV', 'get_ServiceLocator_BBl5klVService', true],
            'App\\Controller\\ReponseController::show' => ['privates', '.service_locator.m9oqhuh', 'get_ServiceLocator_M9oqhuhService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\ReclamationController:delete' => ['privates', '.service_locator..6S4TIj', 'get_ServiceLocator__6S4TIjService', true],
            'App\\Controller\\ReclamationController:edit' => ['privates', '.service_locator..6S4TIj', 'get_ServiceLocator__6S4TIjService', true],
            'App\\Controller\\ReclamationController:index' => ['privates', '.service_locator.5_3wyDn', 'get_ServiceLocator_53wyDnService', true],
            'App\\Controller\\ReclamationController:new' => ['privates', '.service_locator.5_3wyDn', 'get_ServiceLocator_53wyDnService', true],
            'App\\Controller\\ReclamationController:show' => ['privates', '.service_locator.BbAkkvl', 'get_ServiceLocator_BbAkkvlService', true],
            'App\\Controller\\ReponseController:delete' => ['privates', '.service_locator.fgiOSH6', 'get_ServiceLocator_FgiOSH6Service', true],
            'App\\Controller\\ReponseController:edit' => ['privates', '.service_locator.fgiOSH6', 'get_ServiceLocator_FgiOSH6Service', true],
            'App\\Controller\\ReponseController:index' => ['privates', '.service_locator.BBl5klV', 'get_ServiceLocator_BBl5klVService', true],
            'App\\Controller\\ReponseController:new' => ['privates', '.service_locator.BBl5klV', 'get_ServiceLocator_BBl5klVService', true],
            'App\\Controller\\ReponseController:show' => ['privates', '.service_locator.m9oqhuh', 'get_ServiceLocator_M9oqhuhService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\ReclamationController::delete' => '?',
            'App\\Controller\\ReclamationController::edit' => '?',
            'App\\Controller\\ReclamationController::index' => '?',
            'App\\Controller\\ReclamationController::new' => '?',
            'App\\Controller\\ReclamationController::show' => '?',
            'App\\Controller\\ReponseController::delete' => '?',
            'App\\Controller\\ReponseController::edit' => '?',
            'App\\Controller\\ReponseController::index' => '?',
            'App\\Controller\\ReponseController::new' => '?',
            'App\\Controller\\ReponseController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReclamationController:delete' => '?',
            'App\\Controller\\ReclamationController:edit' => '?',
            'App\\Controller\\ReclamationController:index' => '?',
            'App\\Controller\\ReclamationController:new' => '?',
            'App\\Controller\\ReclamationController:show' => '?',
            'App\\Controller\\ReponseController:delete' => '?',
            'App\\Controller\\ReponseController:edit' => '?',
            'App\\Controller\\ReponseController:index' => '?',
            'App\\Controller\\ReponseController:new' => '?',
            'App\\Controller\\ReponseController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
