<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIttsSet\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIttsSet/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIttsSet.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIttsSet\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIttsSet\App_KernelDevDebugContainer([
    'container.build_hash' => 'IttsSet',
    'container.build_id' => '18b9caba',
    'container.build_time' => 1681261287,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIttsSet');
