<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdcx8Zk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdcx8Zk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEdcx8Zk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEdcx8Zk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEdcx8Zk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Edcx8Zk',
    'container.build_id' => 'd6c27cc9',
    'container.build_time' => 1682489487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdcx8Zk');
