<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO4nDbuc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO4nDbuc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO4nDbuc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO4nDbuc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerO4nDbuc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'O4nDbuc',
    'container.build_id' => '4b427346',
    'container.build_time' => 1682456545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO4nDbuc');
