<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGlOv7Za\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGlOv7Za/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGlOv7Za.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGlOv7Za\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGlOv7Za\App_KernelDevDebugContainer([
    'container.build_hash' => 'GlOv7Za',
    'container.build_id' => '192555a2',
    'container.build_time' => 1682487350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGlOv7Za');
